### ISSUE TITLE
[ts-rewrite] Implement samlang source-level interpreter

### ISSUE THREAD

**Issue by SamChou19815** [SamChou19815/samlang#28]
Port [`ExpressionInterpreter`](https://github.com/SamChou19815/samlang/blob/master/samlang-interpreter/src/commonMain/kotlin/samlang/interpreter/ExpressionInterpreter.kt) and [`ModuleInterpreter`](https://github.com/SamChou19815/samlang/blob/master/samlang-interpreter/src/commonMain/kotlin/samlang/interpreter/ModuleInterpreter.kt) to TypeScript, so that we can have a way to test the runtime semantics of the languages.

**Comment by meganyin13** [comment]
yay source-level interpreter is now complete! 🥳
